dummy:
	g++ -fopenmp -o parallel_for_dummy.out parallel_for_dummy.cpp && ./parallel_for_dummy.out
collapse:
	g++ -fopenmp -o parallel_for_collapse.out parallel_for_collapse.cpp && ./parallel_for_collapse.out
atomic:
	g++ -fopenmp -o parallel_for_atomic.out parallel_for_atomic.cpp && ./parallel_for_atomic.out
reduce:
	g++ -fopenmp -o parallel_for_reduce.out parallel_for_reduce.cpp && ./parallel_for_reduce.out
reduce_schedule:
	g++ -fopenmp -o parallel_for_reduce_schedule.out parallel_for_reduce_schedule.cpp && ./parallel_for_reduce_schedule.out